# This is a basic workflow to help you get started with Actions

name: PR CI pipeline

on:
  pull_request:
    branches: ['dev']

jobs:
  ci:
    name: eslint & test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - run: npm run build --if-present
      - name: Eslint
        run: npm run lint
      - name: Test
        env:
          NODE_ENV: ${{ secrets.NODE_ENV }}
          API_ROOT: ${{ secrets.API_ROOT }}
          CORS_ORIGIN: ${{ secrets.CORS_ORIGIN }}
          DB_ADAPTOR: ${{ secrets.DB_ADAPTOR }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
          JWT_EXPIRATION_TIME: ${{ secrets.JWT_EXPIRATION_TIME }}
          IMPORT_KEY: ${{ secrets.IMPORT_KEY }}
          IMPORT_SECRET: ${{ secrets.IMPORT_SECRET }}
          REDIRECT_URI: ${{ secrets.REDIRECT_URI }}
          NAVER_CLIENT_ID: ${{ secrets.NAVER_CLIENT_ID }}
          NAVER_CLIENT_SECRET: ${{ secrets.NAVER_CLIENT_SECRET }}
          NAVER_STATE: ${{ secrets.NAVER_STATE }}
          KAKAO_CLIENT_ID: ${{ secrets.KAKAO_CLIENT_ID }}
          KAKAO_CLIENT_SECRET: ${{ secrets.KAKAO_CLIENT_SECRET }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
        run: npm run test:ci
